# Generated by Django 4.2.11 on 2024-05-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='0501234567', max_length=15, unique=True),
        ),
    ]
