# Generated by Django 4.2.11 on 2024-05-16 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 5, 16, 22, 19, 44, 839143, tzinfo=datetime.timezone.utc), max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
