# Generated by Django 4.2.11 on 2024-05-18 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='root',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='products.category'),
        ),
    ]
