# Generated by Django 4.2.11 on 2024-05-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
